# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Intel Corporation

version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/env/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "America/Los_Angeles"
