# SPDX-License-Identifier: Apache-2.0
# Copyright 2022-Present Intel Corporation
# Copyright 2025 Canonical Ltd.
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v6.0.0

      - name: Setup environment (Hugepages)
        run: |
          sudo sysctl -w vm.nr_hugepages=512
          sudo mkdir -p /mnt/huge
          sudo mount -t hugetlbfs nodev /mnt/huge

      - name: Setup dependencies using Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          sudo ansible-playbook env/cndp.yml -i "localhost," -c local
          sudo ansible-playbook env/ci.yml -i "localhost," -c local
          export VER_CXX=g++
          export CXX="ccache $VER_CXX"
          ccache -s

      - name: Build BESS
        env:
          PKG_CONFIG_PATH: /usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig
        run: |
          sudo -E PKG_CONFIG_PATH=$PKG_CONFIG_PATH ./build.py bess
          sudo ./build.py kmod

      - name: Test BESS
        env:
          BESS_DPDK_DISABLE: "1"
        run: |
          (cd core && ./all_test)
          coverage run -m unittest discover -v
          python3 bessctl/run_module_tests.py
          sudo python3 bessctl/run_module_tests.py --test_dir bessctl/module_tests/cndp
          ccache -s
          bessctl/bessctl daemon stop
          [[ ${COVERAGE:-0} == 0 ]] || { sleep 3; codecov --gcov-exec gcov-7; }
