# SPDX-License-Identifier: Apache-2.0
# Copyright 2022-Present Intel Corporation
# Copyright 2025 Canonical Ltd.
name: CI Build & Test Pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    uses: omec-project/.github/.github/workflows/bess-build-test.yml@40ff5b9cd1d59e64caae6f30ed9ccbece3951ea6 # v0.0.17
    with:
      branch_name: ${{ github.ref }}
